#!/usr/bin/env python3
"""Read-only audit for .skill-runtimes.json version 1."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
MARKER = "generated by"


class ConfigError(Exception):
    pass


def load_config(root: Path, config_path: Path) -> dict:
    path = config_path if config_path.is_absolute() else root / config_path
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ConfigError(f"cannot read config {path}: {exc}") from exc
    if data.get("version") != 1:
        raise ConfigError("manifest version must be 1")
    if not isinstance(data.get("canonical"), str) or not isinstance(data.get("published"), list):
        raise ConfigError("manifest requires canonical string and published array")
    if not isinstance(data.get("targets"), dict) or not data["targets"]:
        raise ConfigError("manifest requires non-empty targets object")
    if len(data["published"]) != len(set(data["published"])):
        raise ConfigError("published skill names must be unique")
    for name in data["published"]:
        if not isinstance(name, str) or not NAME_RE.fullmatch(name):
            raise ConfigError(f"invalid published skill name: {name!r}")
    for runtime, target in data["targets"].items():
        if not isinstance(target, dict) or target.get("format") not in {"directory", "cursor-rule"}:
            raise ConfigError(f"invalid target for {runtime}")
        if not isinstance(target.get("path"), str):
            raise ConfigError(f"target {runtime} requires path")
    return data


def skill_body(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ConfigError(f"canonical skill lacks YAML frontmatter: {path}")
    parts = text.split("---", 2)
    if len(parts) != 3 or not re.search(r"^name:\s*\S+", parts[1], re.M) or not re.search(r"^description:\s*\S+", parts[1], re.M):
        raise ConfigError(f"canonical skill has invalid frontmatter: {path}")
    return parts[2].lstrip("\n")


def compare_dirs(source: Path, target: Path) -> bool:
    def files(base: Path) -> dict[str, bytes]:
        return {str(p.relative_to(base)): p.read_bytes() for p in base.rglob("*") if p.is_file()}
    return files(source) == files(target)


def audit(root: Path, config: dict) -> list[dict[str, str]]:
    findings: list[dict[str, str]] = []
    canonical = root / config["canonical"]
    published = set(config["published"])
    valid_sources: dict[str, Path] = {}
    for name in config["published"]:
        source = canonical / name
        skill = source / "SKILL.md"
        if not skill.is_file():
            findings.append({"kind": "missing", "skill": name, "runtime": "canonical", "path": str(skill)})
            continue
        skill_body(skill)
        valid_sources[name] = source

    for runtime, spec in config["targets"].items():
        base = root / spec["path"]
        for name in config["published"]:
            source = valid_sources.get(name)
            if source is None:
                continue
            if spec["format"] == "directory":
                target = base / name
                if not target.is_dir():
                    findings.append({"kind": "missing", "skill": name, "runtime": runtime, "path": str(target)})
                elif not compare_dirs(source, target):
                    findings.append({"kind": "stale", "skill": name, "runtime": runtime, "path": str(target)})
            else:
                target = base / f"{name}.mdc"
                if not target.is_file():
                    findings.append({"kind": "missing", "skill": name, "runtime": runtime, "path": str(target)})
                else:
                    content = target.read_text(encoding="utf-8")
                    body = skill_body(source / "SKILL.md")
                    if MARKER not in content or f".claude/skills/{name}/SKILL.md" not in content or not content.endswith(body):
                        findings.append({"kind": "stale", "skill": name, "runtime": runtime, "path": str(target)})

        if base.is_dir():
            if spec["format"] == "directory":
                for path in (p for p in base.iterdir() if p.is_dir()):
                    if path.name not in published and not (canonical / path.name / "SKILL.md").is_file() and (path / "SKILL.md").is_file():
                        findings.append({"kind": "orphan", "skill": path.name, "runtime": runtime, "path": str(path)})
            else:
                for path in base.glob("*.mdc"):
                    if path.stem not in published and MARKER in path.read_text(encoding="utf-8", errors="replace"):
                        findings.append({"kind": "orphan", "skill": path.stem, "runtime": runtime, "path": str(path)})
    return findings


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("check", "matrix"))
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--config", type=Path, default=Path(".skill-runtimes.json"))
    parser.add_argument("--json", action="store_true", dest="as_json")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    try:
        config = load_config(root, args.config)
        findings = audit(root, config)
    except ConfigError as exc:
        print(json.dumps({"status": "invalid", "error": str(exc)}) if args.as_json else f"INVALID: {exc}")
        return 2
    payload = {"status": "conformant" if not findings else "drift", "findings": findings}
    if args.as_json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    elif not findings:
        print("skill runtimes conform")
    else:
        for finding in findings:
            print(f"{finding['kind'].upper()}: {finding['runtime']}:{finding['skill']} {finding['path']}")
    return 0 if args.command == "matrix" or not findings else 1


if __name__ == "__main__":
    sys.exit(main())
